# Generated by Django 5.2.4 on 2025-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
            ],
        ),
    ]
