# Generated by Django 5.2.4 on 2025-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeetCodeStats',
        ),
    ]
